version: "3.9"
services:
  exadelmyapp:
    image: shukrulloabdukodirov/exdelmyapp:latest
    ports:
      - '81:80'
  server:
    image: shukrulloabdukodirov/backendjavaapp:1.0
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeedb?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  springmysql-net:




