version: "3.9"
services:
  exadelmyapp:
    image: shukrulloabdukodirov/exdelmyapp:latest
    ports:
      - '81:80'
  server:
    image: shukrulloabdukodirov/backendjavaapp
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeedb?useSSL=false
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234



